"""init

Revision ID: ff6b9fc278d9
Revises: 
Create Date: 2026-05-27 11:41:44.344354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff6b9fc278d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('sanitized_query', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('chunks_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_used', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_inr', sa.Float(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('block_reason', sa.Text(), nullable=True),
    sa.Column('grounding_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('audit_created_idx', 'audit_logs', ['created_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=True),
    sa.Column('policy_date', sa.Date(), nullable=True),
    sa.Column('amendment_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('officer_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_hash'),
    sa.UniqueConstraint('filename')
    )
    op.create_table('officers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('designation', sa.String(length=256), nullable=True),
    sa.Column('ministry', sa.String(length=256), nullable=True),
    sa.Column('tenure_start', sa.Date(), nullable=True),
    sa.Column('tenure_end', sa.Date(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('pages_doc_page_idx', 'pages', ['doc_id', 'page_no'], unique=False)
    op.create_index('pages_fts_idx', 'pages', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('chunks_doc_idx', 'chunks', ['doc_id'], unique=False)
    op.create_index('chunks_vector_idx', 'chunks', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('chunks_vector_idx', table_name='chunks', postgresql_using='ivfflat', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    op.drop_index('chunks_doc_idx', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('pages_fts_idx', table_name='pages', postgresql_using='gin')
    op.drop_index('pages_doc_page_idx', table_name='pages')
    op.drop_table('pages')
    op.drop_table('officers')
    op.drop_table('documents')
    op.drop_index('audit_created_idx', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
